/* JP Express – destinations dataset. Add a country = add one object.
   v: service letters (e express, o economy, d door-to-door, a air, s sea, x export, c customs)
   Transit = express estimate only. Verify rules before publishing. */
const SERVICES = {
  e: { n: 'Express Courier', i: 'fa-bolt', u: 'services.html#intl-courier', f: 'Time-sensitive documents and parcels', c: 'Speed vs. cost' },
  o: { n: 'Economy Courier', i: 'fa-box', u: 'services.html#intl-courier', f: 'Less urgent parcels', c: 'Longer transit, lower cost' },
  d: { n: 'Door-to-Door Delivery', i: 'fa-door-open', u: 'services.html#intl-courier', f: 'Pickup in Bangladesh to recipient address', c: 'Address accuracy' },
  a: { n: 'Air Freight', i: 'fa-plane', u: 'services.html#freight', f: 'Commercial cargo', c: 'Weight / volume' },
  s: { n: 'Sea Freight', i: 'fa-ship', u: 'services.html#freight', f: 'Large, non-urgent cargo', c: 'Transit time / volume' },
  x: { n: 'Commercial Export', i: 'fa-file-export', u: 'services.html#export', f: 'Samples, B2B and export shipments', c: 'Export documents' },
  c: { n: 'Customs Clearance', i: 'fa-stamp', u: 'services.html#import', f: 'Declarations and clearance support', c: 'Duties and taxes' }
};
const ALL = 'eodasxc';
const COUNTRY_DATA = {
  usa: { n: 'United States', c: 'us', r: 'North America', cap: 'Washington, D.C.', cur: 'USD', t: '3–5 days', pop: 1, v: ALL,
    ov: 'One of our busiest routes, used by families sending gifts and documents as well as exporters sending samples and commercial cargo.',
    cu: 'Personal and commercial shipments are handled differently, so declare contents and value accurately. Duties, taxes and importer details depend on the goods and current US import rules.',
    rs: ['Food, plant and animal products', 'Medicines and supplements', 'Lithium batteries and liquids'],
    ch: 'A complete street address, ZIP code and reachable phone number prevent most delays. Remote areas may need extra time.',
    ind: ['Garments & Textile', 'E-commerce', 'Leather & Handicrafts'], ci: 'New York, Los Angeles, Chicago, Houston, Dallas' },
  uk: { n: 'United Kingdom', c: 'gb', r: 'Europe', cap: 'London', cur: 'GBP', t: '3–5 days', pop: 1, v: ALL,
    ov: 'A key destination for Bangladeshi families, students and online sellers, with regular document, parcel and commercial shipments.',
    cu: 'Shipments need an accurate customs declaration. Import VAT and duty depend on value and goods; commercial importers may need an EORI number.',
    rs: ['Meat, dairy and plant products', 'Medicines and cosmetics', 'Batteries and aerosols'],
    ch: 'Recipients may be asked to pay import charges before delivery, so share their contact details early.',
    ind: ['Garments & Textile', 'E-commerce', 'Buying Houses'], ci: 'London, Birmingham, Manchester, Leeds' },
  canada: { n: 'Canada', c: 'ca', r: 'North America', cap: 'Ottawa', cur: 'CAD', t: '4–6 days', pop: 1, v: ALL,
    ov: 'Popular with families and students sending personal parcels, plus small businesses shipping samples and stock.',
    cu: 'Duties and taxes depend on declared value, goods and current Canadian import rules. A correct description and value avoid clearance delays.',
    rs: ['Food and agricultural items', 'Medicines and health products', 'Firearms, weapons and replicas'],
    ch: 'Winter weather and long rural distances can add time outside major cities.',
    ind: ['E-commerce', 'Garments & Textile', 'SMEs'], ci: 'Toronto, Vancouver, Montreal, Calgary' },
  australia: { n: 'Australia', c: 'au', r: 'Asia-Pacific', cap: 'Canberra', cur: 'AUD', t: '5–7 days', pop: 1, v: ALL,
    ov: 'A strong route for personal parcels and gifts, with a growing number of business and sample shipments.',
    cu: 'Biosecurity is strict: food, plant, seed and wooden items must be declared. Import GST and duty depend on value and goods.',
    rs: ['Food, seeds and plant material', 'Wooden and bamboo items', 'Medicines and supplements'],
    ch: 'Remote and regional addresses can take longer than capital cities.',
    ind: ['Garments & Textile', 'Handicrafts', 'E-commerce'], ci: 'Sydney, Melbourne, Brisbane, Perth' },
  uae: { n: 'United Arab Emirates', c: 'ae', r: 'Middle East', cap: 'Abu Dhabi', cur: 'AED', t: '2–3 days', pop: 1, v: ALL,
    ov: 'Our fastest-moving Gulf route, widely used by expatriate families, freelancers and traders.',
    cu: 'Customs may ask for recipient ID or company details, and a clear invoice for goods. Charges depend on goods and value.',
    rs: ['Alcohol, pork and tobacco products', 'Medicines and supplements', 'Religious or restricted media'],
    ch: 'Use a precise delivery location and a phone number the courier can reach; many addresses are landmark-based.',
    ind: ['Garments & Textile', 'E-commerce', 'Food & Agro (subject to rules)'], ci: 'Dubai, Abu Dhabi, Sharjah' },
  saudi: { n: 'Saudi Arabia', c: 'sa', r: 'Middle East', cap: 'Riyadh', cur: 'SAR', t: '3–4 days', pop: 1, v: ALL,
    ov: 'A major destination for expatriate families and importers of apparel, household and consumer goods.',
    cu: 'Some goods need conformity certification (such as SASO/SABER) and commercial invoices must be precise. Confirm before booking.',
    rs: ['Alcohol, pork and religious items', 'Medicines and supplements', 'Electronics needing certification'],
    ch: 'Recipient identification and a detailed national address make final delivery smoother.',
    ind: ['Garments & Textile', 'Handicrafts', 'SMEs'], ci: 'Riyadh, Jeddah, Dammam' },
  germany: { n: 'Germany', c: 'de', r: 'Europe', cap: 'Berlin', cur: 'EUR', t: '3–5 days', v: ALL,
    ov: 'An important EU gateway for garment buyers, e-commerce sellers and families.',
    cu: 'Imports into the EU involve customs declarations and import VAT. Commercial shipments may need an EORI number.',
    rs: ['Food and animal products', 'Medicines and cosmetics', 'Batteries and liquids'],
    ch: 'Clear recipient name and street details reduce redelivery attempts.',
    ind: ['Garments & Textile', 'Leather', 'E-commerce'], ci: 'Berlin, Hamburg, Munich, Frankfurt' },
  france: { n: 'France', c: 'fr', r: 'Europe', cap: 'Paris', cur: 'EUR', t: '3–5 days', v: ALL,
    ov: 'A steady route for personal parcels, fashion samples and small commercial shipments.',
    cu: 'EU customs declarations and import VAT apply. Commercial shipments may need an EORI number and a detailed invoice.',
    rs: ['Food and animal products', 'Medicines and cosmetics', 'Batteries and liquids'],
    ch: 'Share an apartment/door code where relevant so the courier can deliver first time.',
    ind: ['Garments & Textile', 'Handicrafts', 'E-commerce'], ci: 'Paris, Lyon, Marseille' },
  italy: { n: 'Italy', c: 'it', r: 'Europe', cap: 'Rome', cur: 'EUR', t: '4–6 days', v: ALL,
    ov: 'A well-used European route with a large Bangladeshi community and active apparel trade.',
    cu: 'EU customs declarations and import VAT apply; invoices should describe fabric and goods clearly.',
    rs: ['Food and animal products', 'Medicines and cosmetics', 'Counterfeit-brand goods'],
    ch: 'Southern regions and islands can add transit time.',
    ind: ['Garments & Textile', 'Leather', 'Buying Houses'], ci: 'Rome, Milan, Naples' },
  japan: { n: 'Japan', c: 'jp', r: 'Asia-Pacific', cap: 'Tokyo', cur: 'JPY', t: '3–5 days', v: ALL,
    ov: 'Used for documents, student parcels and business samples to a quality-focused market.',
    cu: 'Plant and food quarantine is strict, and customs expects accurate descriptions and values.',
    rs: ['Food, plants and seeds', 'Medicines and supplements', 'Counterfeit or imitation goods'],
    ch: 'Japanese-format addresses and a recipient phone number help delivery.',
    ind: ['Garments & Textile', 'Jute Products', 'Handicrafts'], ci: 'Tokyo, Osaka, Nagoya' },
  southkorea: { n: 'South Korea', c: 'kr', r: 'Asia-Pacific', cap: 'Seoul', cur: 'KRW', t: '3–5 days', v: ALL,
    ov: 'A fast-growing route for students, workers and business samples.',
    cu: 'Individual recipients may need a personal customs clearance code. Duties depend on goods and value.',
    rs: ['Food and agricultural items', 'Medicines and supplements', 'Cosmetics in volume'],
    ch: 'Keep the recipient’s Korean contact details ready for customs.',
    ind: ['Garments & Textile', 'E-commerce', 'SMEs'], ci: 'Seoul, Busan, Incheon' },
  china: { n: 'China', c: 'cn', r: 'Asia-Pacific', cap: 'Beijing', cur: 'CNY', t: '3–5 days', v: 'eodaxc', 
    ov: 'A major sourcing and trade route, mostly business samples, documents and parcels.',
    cu: 'Some commercial goods need import licences or certificates; confirm requirements before dispatch.',
    rs: ['Restricted publications and media', 'Food and medicines', 'Goods needing import licences'],
    ch: 'Provide recipient details in a format customs can verify; address language matters.',
    ind: ['Buying Houses', 'Manufacturing', 'E-commerce'], ci: 'Guangzhou, Shanghai, Beijing' },
  singapore: { n: 'Singapore', c: 'sg', r: 'Asia-Pacific', cap: 'Singapore', cur: 'SGD', t: '2–4 days', v: ALL,
    ov: 'A fast regional hub for documents, parcels and business shipments.',
    cu: 'GST and duty depend on goods and value; controlled items need permits.',
    rs: ['Chewing gum and e-cigarettes', 'Medicines and supplements', 'Controlled or regulated goods'],
    ch: 'Include unit/postcode details for apartments and offices.',
    ind: ['E-commerce', 'SMEs', 'Garments & Textile'], ci: 'Singapore' },
  malaysia: { n: 'Malaysia', c: 'my', r: 'Asia-Pacific', cap: 'Kuala Lumpur', cur: 'MYR', t: '3–5 days', v: ALL,
    ov: 'A popular route for workers, students and traders with strong two-way links.',
    cu: 'Duties and taxes depend on goods and value; certain goods need permits.',
    rs: ['Pork and alcohol products', 'Medicines and supplements', 'Controlled or regulated goods'],
    ch: 'Add postcode and a reachable mobile number for last-mile delivery.',
    ind: ['Garments & Textile', 'E-commerce', 'SMEs'], ci: 'Kuala Lumpur, Penang, Johor Bahru' }
};
const REGIONS = ['North America', 'Europe', 'Middle East', 'Asia-Pacific'];