/* Shared country dataset — add more entries to reach 30+ pages */
const COUNTRY_DATA = {
  usa: { name: "United States", flag: "🇺🇸", region: "North America", capital: "Washington D.C.", currency: "USD", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight (FCL/LCL)", "E-commerce & Amazon FBA"],
    docs: ["Commercial Invoice", "Packing List", "Certificate of Origin (for freight)"],
    restrictions: ["Lithium batteries need declaration", "Food/agricultural items restricted", "Cash & negotiable instruments prohibited"],
    pricing: [{ tier: "Documents (0.5kg)", price: "$18 – $25" }, { tier: "Parcel (2kg)", price: "$35 – $55" }, { tier: "Parcel (5kg)", price: "$70 – $95" }],
    faqs: [{ q: "How long does shipping to the USA take?", a: "Express courier typically takes 3–5 business days; air freight 5–8 days; sea freight 25–35 days." }, { q: "Do you deliver to all US states?", a: "Yes, we deliver door-to-door across all 50 states via our courier and freight partners." }] },
  canada: { name: "Canada", flag: "🇨🇦", region: "North America", capital: "Ottawa", currency: "CAD", transit: "4–6 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"],
    docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Duties apply above CAD $20", "Firearms & weapons prohibited"],
    pricing: [{ tier: "Documents (0.5kg)", price: "$20 – $28" }, { tier: "Parcel (2kg)", price: "$38 – $58" }, { tier: "Parcel (5kg)", price: "$75 – $100" }],
    faqs: [{ q: "What's the delivery time to Canada?", a: "Express courier takes 4–6 business days from Dhaka." }] },
  uk: { name: "United Kingdom", flag: "🇬🇧", region: "Europe", capital: "London", currency: "GBP", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"],
    docs: ["Commercial Invoice", "EORI Number (for commercial shipments)"],
    restrictions: ["VAT applies above £135", "Perishables require special permits"],
    pricing: [{ tier: "Documents (0.5kg)", price: "£14 – £20" }, { tier: "Parcel (2kg)", price: "£28 – £42" }, { tier: "Parcel (5kg)", price: "£55 – £78" }],
    faqs: [{ q: "How long to ship to the UK?", a: "Express courier takes 3–5 business days." }] },
  australia: { name: "Australia", flag: "🇦🇺", region: "Oceania", capital: "Canberra", currency: "AUD", transit: "5–7 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"],
    docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Strict biosecurity on food, plant & wood items", "GST applies above AUD $1000"],
    pricing: [{ tier: "Documents (0.5kg)", price: "$22 – $30" }, { tier: "Parcel (2kg)", price: "$42 – $62" }, { tier: "Parcel (5kg)", price: "$80 – $110" }],
    faqs: [{ q: "Any restricted items for Australia?", a: "Australia has strict biosecurity rules — food, plant, seed and wood packaging need declaration." }] },
  germany: { name: "Germany", flag: "🇩🇪", region: "Europe", capital: "Berlin", currency: "EUR", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "EORI Number"],
    restrictions: ["VAT applies above €150"], pricing: [{ tier: "Documents (0.5kg)", price: "€16 – €22" }, { tier: "Parcel (2kg)", price: "€30 – €45" }, { tier: "Parcel (5kg)", price: "€58 – €80" }],
    faqs: [{ q: "Delivery time to Germany?", a: "3–5 business days via express courier." }] },
  france: { name: "France", flag: "🇫🇷", region: "Europe", capital: "Paris", currency: "EUR", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "EORI Number"],
    restrictions: ["VAT applies above €150"], pricing: [{ tier: "Documents (0.5kg)", price: "€16 – €22" }, { tier: "Parcel (2kg)", price: "€30 – €45" }, { tier: "Parcel (5kg)", price: "€58 – €80" }],
    faqs: [{ q: "Delivery time to France?", a: "3–5 business days via express courier." }] },
  italy: { name: "Italy", flag: "🇮🇹", region: "Europe", capital: "Rome", currency: "EUR", transit: "4–6 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "EORI Number"],
    restrictions: ["VAT applies above €150"], pricing: [{ tier: "Documents (0.5kg)", price: "€17 – €23" }, { tier: "Parcel (2kg)", price: "€32 – €47" }, { tier: "Parcel (5kg)", price: "€60 – €85" }],
    faqs: [{ q: "Delivery time to Italy?", a: "4–6 business days via express courier." }] },
  uae: { name: "United Arab Emirates", flag: "🇦🇪", region: "Middle East", capital: "Abu Dhabi", currency: "AED", transit: "2–3 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Alcohol & pork products restricted"], pricing: [{ tier: "Documents (0.5kg)", price: "$12 – $18" }, { tier: "Parcel (2kg)", price: "$25 – $38" }, { tier: "Parcel (5kg)", price: "$48 – $65" }],
    faqs: [{ q: "Fastest route to UAE?", a: "Air freight and express courier take just 2–3 days from Dhaka to Dubai/Abu Dhabi." }] },
  saudi: { name: "Saudi Arabia", flag: "🇸🇦", region: "Middle East", capital: "Riyadh", currency: "SAR", transit: "3–4 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "SASO Certificate (select goods)"],
    restrictions: ["Alcohol, pork & religious items prohibited"], pricing: [{ tier: "Documents (0.5kg)", price: "$14 – $20" }, { tier: "Parcel (2kg)", price: "$28 – $42" }, { tier: "Parcel (5kg)", price: "$52 – $72" }],
    faqs: [{ q: "Delivery time to Saudi Arabia?", a: "3–4 business days via express courier or air freight." }] },
  japan: { name: "Japan", flag: "🇯🇵", region: "East Asia", capital: "Tokyo", currency: "JPY", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Strict plant & food quarantine rules"], pricing: [{ tier: "Documents (0.5kg)", price: "$18 – $24" }, { tier: "Parcel (2kg)", price: "$34 – $50" }, { tier: "Parcel (5kg)", price: "$65 – $88" }],
    faqs: [{ q: "Delivery time to Japan?", a: "3–5 business days via express courier." }] },
  southkorea: { name: "South Korea", flag: "🇰🇷", region: "East Asia", capital: "Seoul", currency: "KRW", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Duties apply above ~$150"], pricing: [{ tier: "Documents (0.5kg)", price: "$17 – $23" }, { tier: "Parcel (2kg)", price: "$32 – $48" }, { tier: "Parcel (5kg)", price: "$60 – $82" }],
    faqs: [{ q: "Delivery time to South Korea?", a: "3–5 business days via express courier." }] },
  china: { name: "China", flag: "🇨🇳", region: "East Asia", capital: "Beijing", currency: "CNY", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Import licenses required for select commercial goods"], pricing: [{ tier: "Documents (0.5kg)", price: "$15 – $21" }, { tier: "Parcel (2kg)", price: "$28 – $42" }, { tier: "Parcel (5kg)", price: "$52 – $74" }],
    faqs: [{ q: "Delivery time to China?", a: "3–5 business days via express courier." }] },
  singapore: { name: "Singapore", flag: "🇸🇬", region: "Southeast Asia", capital: "Singapore", currency: "SGD", transit: "2–4 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["GST applies above SGD $400"], pricing: [{ tier: "Documents (0.5kg)", price: "$13 – $19" }, { tier: "Parcel (2kg)", price: "$26 – $40" }, { tier: "Parcel (5kg)", price: "$48 – $68" }],
    faqs: [{ q: "Delivery time to Singapore?", a: "2–4 business days via express courier." }] },
  malaysia: { name: "Malaysia", flag: "🇲🇾", region: "Southeast Asia", capital: "Kuala Lumpur", currency: "MYR", transit: "3–5 Days", popular: true,
    services: ["International Courier", "Air Freight", "Sea Freight"], docs: ["Commercial Invoice", "Packing List"],
    restrictions: ["Duties apply above MYR 500"], pricing: [{ tier: "Documents (0.5kg)", price: "$13 – $19" }, { tier: "Parcel (2kg)", price: "$26 – $39" }, { tier: "Parcel (5kg)", price: "$48 – $66" }],
    faqs: [{ q: "Delivery time to Malaysia?", a: "3–5 business days via express courier." }] }
};